#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
 cp -rf 0.org 0
runApplication blockMesh
runApplication setFields
#runApplication decomposePar
runApplication hybridPorousPimpleSEFoam
#runApplication mpirun -n 8 hybridPorousInterHTFoam
